import type { LucideIcon, LucideProps } from "lucide-react";
import {
  Baby,
  BadgeIndianRupee,
  Banknote,
  Bike,
  BookOpen,
  BriefcaseBusiness,
  Bus,
  Car,
  CarFront,
  ChartNoAxesCombined,
  CircleDollarSign,
  CircleEllipsis,
  Clapperboard,
  Coffee,
  Dog,
  Dumbbell,
  Feather,
  Gift,
  Goal,
  GraduationCap,
  HandCoins,
  HeartPulse,
  House,
  Landmark,
  Laptop,
  PawPrint,
  PiggyBank,
  Plane,
  PlugZap,
  Receipt,
  RotateCcw,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  Smartphone,
  Sparkles,
  Store,
  Ticket,
  TrainFront,
  TrendingUp,
  Umbrella,
  Utensils,
  WalletCards,
  Wifi,
  Wrench,
  Zap,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  baby: Baby,
  "badge-indian-rupee": BadgeIndianRupee,
  banknote: Banknote,
  bike: Bike,
  "book-open": BookOpen,
  "briefcase-business": BriefcaseBusiness,
  bus: Bus,
  car: Car,
  "car-front": CarFront,
  "chart-no-axes-combined": ChartNoAxesCombined,
  "circle-dollar-sign": CircleDollarSign,
  "circle-ellipsis": CircleEllipsis,
  clapperboard: Clapperboard,
  coffee: Coffee,
  dog: Dog,
  dumbbell: Dumbbell,
  gift: Gift,
  goal: Goal,
  "graduation-cap": GraduationCap,
  "hand-coins": HandCoins,
  "heart-pulse": HeartPulse,
  house: House,
  landmark: Landmark,
  laptop: Laptop,
  "paw-print": PawPrint,
  "piggy-bank": PiggyBank,
  plane: Plane,
  "plug-zap": PlugZap,
  receipt: Receipt,
  "rotate-ccw": RotateCcw,
  "shield-check": ShieldCheck,
  shirt: Shirt,
  "shopping-bag": ShoppingBag,
  "shopping-basket": ShoppingBasket,
  smartphone: Smartphone,
  sparkles: Sparkles,
  store: Store,
  ticket: Ticket,
  "train-front": TrainFront,
  "trending-up": TrendingUp,
  umbrella: Umbrella,
  utensils: Utensils,
  "wallet-cards": WalletCards,
  wifi: Wifi,
  wrench: Wrench,
  zap: Zap,
};

export function NamedIcon({ name, ...props }: LucideProps & { name?: string | null }) {
  const Icon = (name && iconMap[name]) || CircleDollarSign;
  return <Icon aria-hidden="true" {...props} />;
}

export function BrandMark({ size = 40 }: { size?: number }) {
  return (
    <span className="brand-mark" style={{ width: size, height: size }} aria-hidden="true">
      <Feather size={Math.round(size * 0.56)} strokeWidth={2.4} />
    </span>
  );
}
